# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merge_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Merge_QDialog(object):
    def setupUi(self, Merge_QDialog):
        Merge_QDialog.setObjectName("Merge_QDialog")
        Merge_QDialog.resize(675, 418)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/PDF合并.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Merge_QDialog.setWindowIcon(icon)
        self.pushButton_w2_add = QtWidgets.QPushButton(Merge_QDialog)
        self.pushButton_w2_add.setGeometry(QtCore.QRect(560, 20, 100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.pushButton_w2_add.setFont(font)
        self.pushButton_w2_add.setObjectName("pushButton_w2_add")
        self.pushButton_w2_remove = QtWidgets.QPushButton(Merge_QDialog)
        self.pushButton_w2_remove.setGeometry(QtCore.QRect(560, 70, 100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.pushButton_w2_remove.setFont(font)
        self.pushButton_w2_remove.setObjectName("pushButton_w2_remove")
        self.pushButton_w2_up = QtWidgets.QPushButton(Merge_QDialog)
        self.pushButton_w2_up.setGeometry(QtCore.QRect(560, 120, 100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.pushButton_w2_up.setFont(font)
        self.pushButton_w2_up.setObjectName("pushButton_w2_up")
        self.pushButton_w2_down = QtWidgets.QPushButton(Merge_QDialog)
        self.pushButton_w2_down.setGeometry(QtCore.QRect(560, 170, 100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.pushButton_w2_down.setFont(font)
        self.pushButton_w2_down.setObjectName("pushButton_w2_down")
        self.pushButton_w2_start = QtWidgets.QPushButton(Merge_QDialog)
        self.pushButton_w2_start.setGeometry(QtCore.QRect(560, 220, 100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.pushButton_w2_start.setFont(font)
        self.pushButton_w2_start.setObjectName("pushButton_w2_start")
        self.progressBar_w2_bar = QtWidgets.QProgressBar(Merge_QDialog)
        self.progressBar_w2_bar.setGeometry(QtCore.QRect(20, 360, 635, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.progressBar_w2_bar.setFont(font)
        self.progressBar_w2_bar.setProperty("value", 0)
        self.progressBar_w2_bar.setObjectName("progressBar_w2_bar")
        self.tableWidget_w2_fileList = QtWidgets.QTableWidget(Merge_QDialog)
        self.tableWidget_w2_fileList.setGeometry(QtCore.QRect(20, 20, 520, 301))
        self.tableWidget_w2_fileList.setLineWidth(0)
        self.tableWidget_w2_fileList.setShowGrid(True)
        self.tableWidget_w2_fileList.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_w2_fileList.setObjectName("tableWidget_w2_fileList")
        self.tableWidget_w2_fileList.setColumnCount(2)
        self.tableWidget_w2_fileList.setRowCount(0)
        self.tableWidget_w2_fileList.setColumnWidth(0, 450)
        self.tableWidget_w2_fileList.setColumnWidth(1, 70)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_w2_fileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_w2_fileList.setHorizontalHeaderItem(1, item)

        self.retranslateUi(Merge_QDialog)
        QtCore.QMetaObject.connectSlotsByName(Merge_QDialog)

    def retranslateUi(self, Merge_QDialog):
        _translate = QtCore.QCoreApplication.translate
        Merge_QDialog.setWindowTitle(_translate("Merge_QDialog", "PDF合并"))
        self.pushButton_w2_add.setText(_translate("Merge_QDialog", "➕添加"))
        self.pushButton_w2_remove.setText(_translate("Merge_QDialog", "➖移除"))
        self.pushButton_w2_up.setText(_translate("Merge_QDialog", "⬆上移"))
        self.pushButton_w2_down.setText(_translate("Merge_QDialog", "⬇下移"))
        self.pushButton_w2_start.setText(_translate("Merge_QDialog", "开始"))
        item = self.tableWidget_w2_fileList.horizontalHeaderItem(0)
        item.setText(_translate("Merge_QDialog", "PDF 文件 ( 0 )"))
        item = self.tableWidget_w2_fileList.horizontalHeaderItem(1)
        item.setText(_translate("Merge_QDialog", "页数"))
import img_rc
